##########################################
# Site Settings
baseURL = "https://matt.copperwaite.net"
languageCode = "en-gb"
title = "Matt Copperwaite"

hasCJKLanguage = false
# Copyright information (Markdown supported)
copyright = "CC BY-SA 4.0"

# Name of theme
theme = "custom"

[pagination]
pagerSize = 5

# URL structure
[permalinks]
blog = "/blog/:year/:month/:day/:title"
personal = "/personal/:year/:month/:day/:title"
categories = "/categories/:slug/"
tags = "/tags/:slug/"

# Taxonomies
[taxonomies]
tag = "tags"

# Maximum number of items in the Atom & RSS feed
[services.rss]
limit = 10

[menu]
## Menu bar
[[menu.main]]
url = "/"
name = "Home"
weight = 1
pre = "internal"
post = "home"
[[menu.main]]
name = "Blogs"
identifier = "blogs"
weight = 2
[[menu.main]]
url = "/blog/"
name = "Security"
weight = 1
parent = "blogs"
pre = "internal"
post = "archive"
[[menu.main]]
url = "/personal/"
name = "Personal"
weight = 2
parent = "blogs"
pre = "internal"
post = "archive"
[[menu.main]]
url = "/showcase/"
name = "Showcase"
weight = 3
pre = "internal"
post = "archive"
[[menu.main]]
url = "/about-me/"
name = "About Me"
weight = 4
pre = "internal"
post = "archive"


##########################################
# Theme Settings

[params]

name = "Matt Copperwaite"


[Webmention]
reply_to = "https://webmention-mc.fly.dev"

# social networks
github = "https://github.com/yaMatt"
linkedin = "https://www.linkedin.com/in/matthew-copperwaite-44319b26"
keybase = "https://keybase.io/mattcopp"
stackoverflow = "https://meta.stackoverflow.com/users/421159/matt-copperwaite"
steam = "https://steamcommunity.com/id/yaMatt/home/"
matrix = "https://matrix.to/#/@yamatt:matrix.org"


socialNetworksOrder = [
    "GitHub",
    "LinkedIn",
    "Matrix",
    "Keybase",
    "StackOverflow",
    "Steam",
]
