##########################################
# Site Settings
baseURL = "https://matt.copperwaite.net"
languageCode = "en-gb"
title = "Matt Copperwaite"
copyright = "CC BY-SA 4.0"

# Name of theme
theme = "custom"

[pagination]
pagerSize = 5

# URL structure
[permalinks]
blog = "/blog/:year/:month/:day/:title"
personal = "/personal/:year/:month/:day/:title"
categories = "/categories/:slug/"
tags = "/tags/:slug/"

# Taxonomies
[taxonomies]
tag = "tags"

# Maximum number of items in the Atom & RSS feed
[services.rss]
limit = 10

[menu]
## Menu bar
[[menu.main]]
url = "/"
name = "Home"
weight = 1
pre = "internal"
post = "home"
[[menu.main]]
name = "Blogs"
identifier = "blogs"
weight = 2
[[menu.main]]
url = "/blog/"
name = "Security"
weight = 1
parent = "blogs"
pre = "internal"
post = "archive"
[[menu.main]]
url = "/personal/"
name = "Personal"
weight = 2
parent = "blogs"
pre = "internal"
post = "archive"
[[menu.main]]
url = "/showcase/"
name = "Showcase"
weight = 3
pre = "internal"
post = "archive"
[[menu.main]]
url = "/about-me/"
name = "About Me"
weight = 4
pre = "internal"
post = "archive"

##########################################
# Outputs

[outputFormats]
[outputFormats.Markdown]
mediaType = "text/markdown"
isPlainText = true
fileKind = "page"
baseName = "index"
rel = "alternate"

[outputs]
home = ["HTML"]
page = ["HTML", "Markdown"]
section = ["HTML", "RSS"]

##########################################
# Theme Settings

[Params]

author = "Matt Copperwaite"
subtitle = "Secure IT through Agile delivery."

[Params.Webmention]
reply_to = "https://webmention-mc.fly.dev"

[Params.SocialNetworks]
[[Params.SocialNetworks.Social]]
name = "GitHub"
icon = "github"
link = "https://github.com/yaMatt"

[[Params.SocialNetworks.Social]]
name = "LinkedIn"
icon = "linkedin"
link = "https://www.linkedin.com/in/matthew-copperwaite-44319b26"

[[Params.SocialNetworks.Social]]
name = "Keybase"
icon = "keybase"
link = "https://keybase.io/mattcopp"

[[Params.SocialNetworks.Social]]
name = "Mastodon"
icon = "mastodon"
link = "https://mastodon.social/@yayamatt"

[[Params.SocialNetworks.Social]]
name = "StackOverflow"
icon = "stackoverflow"
link = "https://meta.stackoverflow.com/users/421159/matt-copperwaite"

[[Params.SocialNetworks.Social]]
name = "Steam"
icon = "steam"
link = "https://steamcommunity.com/id/yaMatt/home/"

[[Params.SocialNetworks.Social]]
name = "Matrix"
icon = "matrix"
link = "https://matrix.to/#/@yamatt:matrix.org"
